export const REQUEST_DATA = 'REQUEST_DATA';
export const RECEIVED_DATA = 'RECEIVED_DATA';
export const HANDLE_NAME_FILTER = 'HANDLE_NAME_FILTER';
export const HANDLE_CHANGE_NUMERIC = 'HANDLE_CHANGE_NUMERIC';
export const SUBMIT_FILTER = 'SUBMIT_FILTER';
export const REMOVE_FILTER = 'REMOVE_FILTER';
