const REQUEST_PLANETS_INFORMATION = 'REQUEST_PLANETS_INFORMATION';

const PLANET_INFO_REQUEST_SUCCESS = 'PLANET_INFO_REQUEST_SUCCESS';

const PLANET_INFO_REQUEST_FAILURE = 'PLANET_INFO_REQUEST_FAILURE';

const FILTER_BY_TEXT = 'FILTER_BY_TEXT';

const SAVE_FILTER_DATA = 'SAVE_FILTER_DATA';

export {
  REQUEST_PLANETS_INFORMATION,
  PLANET_INFO_REQUEST_SUCCESS,
  PLANET_INFO_REQUEST_FAILURE,
  FILTER_BY_TEXT,
  SAVE_FILTER_DATA,
};
