export const ACTION_GET_API = 'ACTION_GET_API';
export const ACTION_SUCESS = 'ACTION_SUCESS';
export const ACTION_FAILURE = 'ACTION_FAILURE';
export const FILTERED_NAME = 'FILTERED_NAME';
export const FILTERED_NUMERIC = 'FILTERED_NUMERIC';
export const FILTERED_VALUES = 'FILTERED_VALUES';
export const DELETE_FILTER = 'DELETE_FILTER';
