export const REQUEST_PLANETS = 'REQUEST_PLANETS';
export const SUCCESS_PLANETS = 'SUCCESS_PLANETS';
export const FAILURE_PLANETS = 'FAILURE_PLANETS';
export const FILTERED_NAME = 'FILTERED_NAME';
export const FILTERED_NUMERIC = 'FILTERED_NUMERIC';
export const FILTERED_VALUES = 'FILTERED_VALUES';
